### ISSUE TITLE
Time prasing exception in `io.event_log`

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/pix-framework#20]
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/usr/src/Simod/src/simod/simulation/prosimos.py", line 225, in _read_simulated_log
    df = read_csv_log(log_path, log_ids=log_ids)
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/pix_framework/io/event_log.py", line 103, in read_csv_log
    event_log[log_ids.end_time] = pd.to_datetime(event_log[log_ids.end_time], utc=True, format="ISO8601")
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 1112, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 488, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
  File "/usr/src/Simod/.venv/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 519, in _array_strptime_with_fallback
    result, timezones = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
  File "strptime.pyx", line 534, in pandas._libs.tslibs.strptime.array_strptime
  File "strptime.pyx", line 349, in pandas._libs.tslibs.strptime.array_strptime
ValueError: Time data 2 is not ISO8601 format, at position 219980. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
```

**Comment by iharsuvorau** [comment]
Not sure about this issue yet. Recently, I've run out of disk space on the benchmark server. This issue might be related to this (e.g., corrupted log file from Prosimos because of no space). Confirming it now.
